name: Binary Cache

on: [push, pull_request, workflow_dispatch]
jobs:
  nix:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: nixbuild/nix-quick-install-action@v30
      - uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
      - uses: cachix/cachix-action@v12
        with:
          name: ags
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build ags
        run: |
          nix build --print-build-logs
